# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
oplus_bsp_ist_up-y      += hall_ist8801_up.o
obj-m	+= oplus_bsp_ist_up.o
oplus_bsp_ist_down-y    += hall_ist8801_down.o
obj-m	+= oplus_bsp_ist_down.o
