# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-m	 += oplus_bsp_dfr_pmic_monitor.o
oplus_bsp_dfr_pmic_monitor-objs := oplus_pmic_info_smem.o main.o oplus_pmic_machine_state.o oplus_ocp_dev.o oplus_ocp_state_nvmem.o


