#
# Makefile for the Synaptics TCM touchscreen driver.
#

# Each configuration option enables a list of files.

oplus_bsp_tp_tcm_S3908-y += synaptics_tcm_S3908.o
oplus_bsp_tp_tcm_S3908-y += synaptics_tcm_device_S3908.o

obj-m += oplus_bsp_tp_tcm_S3908.o
