# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.

# Qcom platform feature

#ifdef OPLUS_FEATURE_PMIC_MONITOR
obj-y += qcom/qcom_pmic_monitor/
#endif /* OPLUS_FEATURE_PMIC_MONITOR */

#ifdef OPLUS_FEATURE_QCOM_PMICWD
obj-y += qcom/qcom_pmicwd/
#endif /* OPLUS_FEATURE_QCOM_PMICWD */

#ifdef OPLUS_FEATURE_DUMP_DEVICE_INFO
obj-y	+=  qcom/dump_device_info/
#endif /* OPLUS_FEATURE_DUMP_DEVICE_INFO */

#ifdef OPLUS_FEATURE_DUMP_REASON
obj-y	+=  qcom/dump_reason/
#endif /* OPLUS_FEATURE_DUMP_REASON */

#ifdef OPLUS_FEATURE_KEYEVENT_HANDLER
obj-y += common/keyevent_handler/
#endif /* OPLUS_FEATURE_KEYEVENT_HANDLER */
