#
# Makefile for the tn pogo_keyboard device drivers.
#
#

obj-m		+= oplus_bsp_pogo_keyboard.o
oplus_bsp_pogo_keyboard-y		+= pogo_keyboard_core.o
oplus_bsp_pogo_keyboard-y 	+= keyboard.o touchpad.o pogo_tty_io.o pogo_ota.o
