# SPDX-License-Identifier: GPL-2.0-only

VIDEO_DRIVER_ABS_PATH := $(VIDEO_ROOT)/video/driver
VIDEO_DRIVER_REL_PATH := ../video/driver

ifeq ($(CONFIG_ARCH_KALAMA), y)
include $(VIDEO_ROOT)/config/kalama_video.conf
LINUXINCLUDE    += -include $(VIDEO_ROOT)/config/kalama_video.h \
                   -I$(VIDEO_DRIVER_ABS_PATH)/platform/kalama/inc
endif

LINUXINCLUDE    += -I$(VIDEO_DRIVER_ABS_PATH)/vidc/inc \
                   -I$(VIDEO_DRIVER_ABS_PATH)/platform/common/inc \
                   -I$(VIDEO_DRIVER_ABS_PATH)/variant/common/inc \
                   -I$(VIDEO_ROOT)/include/uapi/vidc

USERINCLUDE     += -I$(VIDEO_ROOT)/include/uapi/vidc/media \
                   -I$(VIDEO_ROOT)/include/uapi/vidc

obj-m += video.o

ifeq ($(CONFIG_MSM_VIDC_KALAMA), y)
video-objs += $(VIDEO_DRIVER_REL_PATH)/platform/kalama/src/kalama.o
endif

ifeq ($(CONFIG_MSM_VIDC_IRIS3), y)
LINUXINCLUDE    += -I$(VIDEO_DRIVER_ABS_PATH)/variant/iris3/inc
video-objs += $(VIDEO_DRIVER_REL_PATH)/variant/iris3/src/msm_vidc_buffer_iris3.o \
                  $(VIDEO_DRIVER_REL_PATH)/variant/iris3/src/msm_vidc_power_iris3.o \
                  $(VIDEO_DRIVER_REL_PATH)/variant/iris3/src/msm_vidc_iris3.o
endif

video-objs += $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_v4l2.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_vb2.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vdec.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_venc.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_driver.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_state.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_control.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_buffer.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_power.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_probe.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/resources.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/firmware.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_debug.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_memory.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/msm_vidc_fence.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/venus_hfi.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/venus_hfi_queue.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/hfi_packet.o \
                  $(VIDEO_DRIVER_REL_PATH)/vidc/src/venus_hfi_response.o \
                  $(VIDEO_DRIVER_REL_PATH)/platform/common/src/msm_vidc_platform.o \
                  $(VIDEO_DRIVER_REL_PATH)/variant/common/src/msm_vidc_variant.o
