#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


oplus_bsp_tp_ft3681-y += ft3681_driver.o
oplus_bsp_tp_ft3681-y += ft3681_test.o
obj-m += oplus_bsp_tp_ft3681.o
