/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#define CONFIG_QCOM_KGSL 1
#define CONFIG_DEVFREQ_GOV_QCOM_ADRENO_TZ 1
#define CONFIG_DEVFREQ_GOV_QCOM_GPUBW_MON 1
#define CONFIG_QCOM_KGSL_IDLE_TIMEOUT 80
#define CONFIG_QCOM_KGSL_SORT_POOL 1
#define CONFIG_QCOM_KGSL_CONTEXT_DEBUG 1
#define CONFIG_QCOM_KGSL_IOCOHERENCY_DEFAULT 1
#define CONFIG_QCOM_ADRENO_DEFAULT_GOVERNOR "msm-adreno-tz"
#define CONFIG_QTI_HW_FENCE 1

#if (IS_ENABLED(CONFIG_SHMEM))
#define CONFIG_QCOM_KGSL_USE_SHMEM 1
#define CONFIG_QCOM_KGSL_PROCESS_RECLAIM 1
#endif

#if (IS_ENABLED(CONFIG_CORESIGHT))
#define CONFIG_QCOM_KGSL_CORESIGHT 1
#endif
