oplus_sensor_interact-y	+=  oplus_ssc_interact.o
obj-m	+=  oplus_sensor_interact.o
ccflags-y := \
	-DCONFIG_OPLUS_SENSOR_FB_QC \
	-DCONFIG_OPLUS_SENSOR_DRM_PANEL_NOTIFY \
	-DCONFIG_OPLUS_SENSOR_DRM_PANEL_ADFR_MIN_FPS \
	-DCONFIG_OPLUS_SENSOR_USE_SCREENSHOT_INFO
