#
# Makefile for the Synaptics TCM touchscreen driver.
#

# Each configuration option enables a list of files.

oplus_bsp_tp_tcm_S3910-y += synaptics_tcm_S3910.o
oplus_bsp_tp_tcm_S3910-y += synaptics_tcm_device_S3910.o

obj-m += oplus_bsp_tp_tcm_S3910.o
