obj-y	+= ist_hall_ic/
obj-y	+= hall_ic/
oplus_bsp_tri_key-y             += oplus_tri_key.o  tri_key_exception.o
oplus_bsp_tri_key-y             += tri_key_healthinfo.o tri_key_common_api.o
obj-m      += oplus_bsp_tri_key.o
obj-y	+= digital_hall_ic/
