#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


oplus_bsp_tp_ft3419u-y += ft3419u_driver.o
oplus_bsp_tp_ft3419u-y += ft3419u_test.o
obj-m += oplus_bsp_tp_ft3419u.o
