# Makefile for the goodix touchscreen drivers.

oplus_bsp_tp_hbp_goodix_gt99x6-y += gt99x6_core.o
oplus_bsp_tp_hbp_goodix_gt99x6-y += gtx8_tools.o
obj-m +=  oplus_bsp_tp_hbp_goodix_gt99x6.o
#obj-$(TOUCHSCREEN_GTS)+= oplus_gt99x6.o
