#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ILITEK_ILITEK9881H_V3) += ilitek9881h/
obj-y += ilitek7807s/

oplus_bsp_tp_ilitek_common-y += ilitek_common.o
obj-m += oplus_bsp_tp_ilitek_common.o
#endif
#endif
