#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


oplus_bsp_tp_ft3683g-y += ft3683g_driver.o
oplus_bsp_tp_ft3683g-y += ft3683g_test.o
obj-m += oplus_bsp_tp_ft3683g.o
