#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


oplus_bsp_tp_ft8057p-y += ft8057p_driver.o
oplus_bsp_tp_ft8057p-y += ft8057p_test.o
obj-m += oplus_bsp_tp_ft8057p.o
